
services:
  mysql:
    image: focker.ir/mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: 927649
    volumes:
      - mysql:/var/lib/mysql
  backend:
    build:
      context: ./back_end
    env_file:
      - ./back.env
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - mysql
    volumes:
      - /root/home/uploads:/app/uploads

  frontend:
    build:
      context: ./front_end
      args:
        REACT_APP_BASE_URL: http://87.107.105.139:5000
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - backend      
    restart: always

volumes:
  mysql:


