name: Deploy to VPS

on:
  push:
    branches:
      - master # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key for VPS
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 87.107.105.139 >> ~/.ssh/known_hosts  # Replace with your VPS IP
          chmod 700 ~/.ssh
          chmod 644 ~/.ssh/known_hosts
      - name: Deploy to VPS
        run: |
          ssh -p 9011 root@87.107.105.139 'bash -s' < ./deploy.sh
